-- ─────────────────────────────────────────────────────────────
--  Nerdlandia — Approved Noun List for Team Names
--  Paste into Supabase SQL Editor after running 01_schema.sql
--
--  Team names: [1–2 digit number] + [noun from this list]
--  e.g. "7 Penguins", "42 Robots", "13 Wizards"
--
--  To ADD a noun: insert into public.noun_list values ('yourword');
--  To REMOVE:     delete from public.noun_list where word = 'yourword';
-- ─────────────────────────────────────────────────────────────

insert into public.noun_list (word) values
-- Animals
('Aardvarks'), ('Alpacas'), ('Armadillos'), ('Axolotls'),
('Badgers'), ('Bats'), ('Bears'), ('Beavers'), ('Bees'),
('Beetles'), ('Buffalos'), ('Butterflies'),
('Camels'), ('Capybaras'), ('Cardinals'), ('Cats'), ('Caterpillars'),
('Chameleons'), ('Cheetahs'), ('Chickens'), ('Chipmunks'), ('Condors'),
('Coyotes'), ('Crabs'), ('Cranes'), ('Crocodiles'), ('Crows'),
('Deer'), ('Dogs'), ('Dolphins'), ('Donkeys'), ('Ducks'),
('Eagles'), ('Eels'), ('Elephants'), ('Emus'),
('Falcons'), ('Ferrets'), ('Flamingos'), ('Foxes'), ('Frogs'),
('Gazelles'), ('Geckos'), ('Geese'), ('Giraffes'), ('Goats'),
('Gorillas'), ('Groundhogs'),
('Hamsters'), ('Hedgehogs'), ('Herons'), ('Hippos'), ('Horses'),
('Hummingbirds'), ('Hyenas'),
('Iguanas'),
('Jackals'), ('Jaguars'), ('Jellyfish'),
('Kangaroos'), ('Koalas'), ('Komodos'),
('Lemurs'), ('Leopards'), ('Lions'), ('Lizards'), ('Llamas'), ('Lobsters'),
('Macaws'), ('Manatees'), ('Meerkats'), ('Moles'), ('Monkeys'), ('Moose'),
('Narwhals'), ('Newts'),
('Octopi'), ('Opossums'), ('Otters'), ('Owls'),
('Pandas'), ('Panthers'), ('Parrots'), ('Peacocks'), ('Penguins'),
('Porcupines'), ('Puffins'),
('Rabbits'), ('Raccoons'), ('Ravens'), ('Rhinos'),
('Salamanders'), ('Seals'), ('Sharks'), ('Sloths'), ('Snails'),
('Sparrows'), ('Squirrels'), ('Storks'), ('Swans'),
('Tigers'), ('Tortoises'), ('Turtles'),
('Vultures'),
('Walruses'), ('Weasels'), ('Wolves'), ('Wombats'), ('Woodpeckers'),
('Yaks'),
('Zebras'),

-- Fantasy / Sci-Fi creatures
('Aliens'), ('Androids'), ('Angels'), ('Automatons'),
('Centaurs'), ('Chimeras'), ('Clones'), ('Cyborgs'),
('Demons'), ('Dragons'), ('Dwarves'),
('Elves'),
('Fairies'), ('Familiars'), ('Gargoyles'), ('Giants'), ('Gnomes'),
('Goblins'), ('Golems'), ('Gremlins'), ('Griffins'),
('Hobbits'), ('Hydras'),
('Imps'),
('Krakens'),
('Mermaids'), ('Minotaurs'),
('Ogres'), ('Orcs'),
('Phoenixes'), ('Pixies'),
('Robots'),
('Satyrs'), ('Sprites'),
('Trolls'),
('Unicorns'),
('Vampires'),
('Wendigos'), ('Werewolves'), ('Witches'), ('Wizards'), ('Wraiths'),
('Zombies'),

-- Objects / Things
('Anchors'), ('Anvils'), ('Arrows'),
('Beacons'), ('Bells'), ('Blades'), ('Blueprints'), ('Boomerangs'), ('Buoys'),
('Cannons'), ('Capsules'), ('Circuits'), ('Cloaks'), ('Clocks'), ('Codices'),
('Coins'), ('Comets'), ('Compasses'), ('Crystals'),
('Daggers'), ('Dice'), ('Diplomas'),
('Engines'),
('Flasks'), ('Flares'), ('Flutes'),
('Gadgets'), ('Gears'), ('Gems'), ('Globes'),
('Hammers'), ('Helmets'), ('Hourglasses'),
('Idols'),
('Journals'),
('Keys'), ('Knives'),
('Lanterns'), ('Lasers'), ('Lenses'), ('Lockets'),
('Magnets'), ('Maps'), ('Masks'), ('Medals'), ('Meteors'), ('Mirrors'),
('Modules'),
('Needles'), ('Notebooks'),
('Orbs'),
('Padlocks'), ('Pendulums'), ('Potions'), ('Prisms'), ('Probes'),
('Puzzles'),
('Radars'), ('Relics'), ('Rockets'), ('Runes'),
('Satellites'), ('Scrolls'), ('Shields'), ('Signals'), ('Spells'),
('Staffs'), ('Stars'), ('Swords'),
('Telescopes'), ('Tokens'), ('Torches'), ('Turbines'),
('Vials'),
('Wands'), ('Whistles'),

-- Abstract / Concepts
('Anomalies'),
('Ciphers'), ('Clues'), ('Codes'),
('Echoes'), ('Enigmas'), ('Equations'),
('Fables'), ('Fractals'),
('Glitches'),
('Hypotheses'),
('Legends'), ('Loops'),
('Myths'),
('Omens'),
('Paradoxes'), ('Patterns'), ('Phenomena'), ('Puzzles'),
('Queries'),
('Riddles'),
('Secrets'), ('Signals'), ('Specters'),
('Theorems'),
('Vectors'),
('Wonders'),

-- Places / Structures
('Arenas'), ('Archives'),
('Bunkers'),
('Castles'), ('Caves'), ('Citadels'),
('Dungeons'),
('Fortresses'),
('Galaxies'),
('Isles'),
('Labyrinths'), ('Libraries'),
('Mazes'),
('Nebulas'),
('Outposts'),
('Portals'),
('Realms'), ('Ruins'),
('Sanctuaries'),
('Temples'), ('Towers'),
('Vaults'),
('Wastelands')

on conflict (word) do nothing;
